// <auto-generated />
using LogWriter;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LogWriter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180425065716_AddValuesMigration")]
    partial class AddValuesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LogWriter.DoubleValue", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Station");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.ToTable("DoubleValue");
                });

            modelBuilder.Entity("LogWriter.StringValue", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Station");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("PrecipitationTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
